/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kyrr30mDmQS
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function HomeComponent() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="bg-gray-900 text-white py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid gap-6 md:grid-cols-2 md:gap-12">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                  Welcome to FeedScrape
                </h1>
                <p className="text-gray-400 md:text-xl">
                  Your Daily Dose of Knowledge: Explore Our Blogs and Feeds. Register Now to get a curated list of feeds and blogs!
                </p>
                <div className="flex flex-col gap-2 sm:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-[#00b894] px-6 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-[#00a185] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#00b894] disabled:pointer-events-none disabled:opacity-50"
                    href="/feeds"
                  >
                    Get Started
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-[#00b894] bg-transparent px-6 text-sm font-medium text-[#00b894] shadow-sm transition-colors hover:bg-[#00b894]/10 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#00b894] disabled:pointer-events-none disabled:opacity-50"
                    href="/register"
                  >
                    Register
                  </Link>
                </div>
              </div>
              <div className="flex items-center justify-center">
                <img
                  alt="Hero"
                  className="max-w-full rounded-lg"
                  height={400}
                  src="https://images.unsplash.com/photo-1554228243-ff1759819ed3?q=80&w=2673&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                  style={{
                    aspectRatio: "400/400",
                    objectFit: "cover",
                  }}
                  width={400}
                />
              </div>
            </div>
          </div>
        </section>
        <section className="bg-gray-100 py-12 md:py-24 lg:py-32">
          <div className="container mx-auto px-4 md:px-6">
            <div className="grid gap-6 md:grid-cols-2 md:gap-12">
              <div className="flex flex-col items-start space-y-4">
                <div className="inline-block rounded-lg bg-[#00b894] px-3 py-1 text-sm text-gray-50">Navigation</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Explore Our App</h2>
                <p className="text-gray-500 md:text-xl">
                  Navigate through our app&apos;s features and discover the tools that can help you achieve your goals.
                </p>
              </div>
              <div className="grid gap-4">
                <Link
                  className="group flex items-center justify-between rounded-lg bg-white p-4 shadow-sm transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
                  href="#"
                >
                  <div className="flex items-center gap-4">
                    <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                      <ActivityIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-medium">Health Check</h3>
                      <p className="text-sm text-gray-500 ">
                        Monitor your app&apos;s health and performance.
                      </p>
                    </div>
                  </div>
                  <ChevronRightIcon className="h-5 w-5 text-gray-500" />
                </Link>
                <Link
                  className="group flex items-center justify-between rounded-lg bg-white p-4 shadow-sm transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
                  href="#"
                >
                  <div className="flex items-center gap-4">
                    <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                      <UserPlusIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-medium">Register</h3>
                      <p className="text-sm text-gray-500 ">
                        Create an account and start using our app.
                      </p>
                    </div>
                  </div>
                  <ChevronRightIcon className="h-5 w-5 text-gray-500" />
                </Link>
                <Link
                  className="group flex items-center justify-between rounded-lg bg-white p-4 shadow-sm transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
                  href="#"
                >
                  <div className="flex items-center gap-4">
                    <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                      <UserIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-medium">Profile</h3>
                      <p className="text-sm text-gray-500 ">
                        Manage your account and personal information.
                      </p>
                    </div>
                  </div>
                  <ChevronRightIcon className="h-5 w-5 text-gray-500" />
                </Link>
                <Link
                  className="group flex items-center justify-between rounded-lg bg-white p-4 shadow-sm transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
                  href="#"
                >
                  <div className="flex items-center gap-4">
                    <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                      <RssIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-medium">Feeds</h3>
                      <p className="text-sm text-gray-500 ">
                        Stay up-to-date with the latest content.
                      </p>
                    </div>
                  </div>
                  <ChevronRightIcon className="h-5 w-5 text-gray-500  " />
                </Link>
                <Link
                  className="group flex items-center justify-between rounded-lg bg-white p-4 shadow-sm transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
                  href="#"
                >
                  <div className="flex items-center gap-4">
                    <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                      <UsersIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-medium">Feed Follows</h3>
                      <p className="text-sm text-gray-500 ">Manage the feeds you follow.</p>
                    </div>
                  </div>
                  <ChevronRightIcon className="h-5 w-5 text-gray-500 " />
                </Link>
                <Link
                  className="group flex items-center justify-between rounded-lg bg-white p-4 shadow-sm transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
                  href="#"
                >
                  <div className="flex items-center gap-4">
                    <div className="rounded-full bg-[#00b894] p-2 text-gray-50">
                      <FilePenIcon className="h-5 w-5" />
                    </div>
                    <div>
                      <h3 className="text-lg font-medium">Posts</h3>
                      <p className="text-sm text-gray-500 ">
                        Create, manage, and interact with posts.
                      </p>
                    </div>
                  </div>
                  <ChevronRightIcon className="h-5 w-5 text-gray-500 " />
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-gray-900 text-white py-6 px-4 md:px-6">
        <div className="container mx-auto flex items-center justify-between">
          <p className="text-sm">© 2024 MyApp</p>
          <nav className="flex items-center gap-4">
            <Link className="hover:underline" href="#">
              Terms
            </Link>
            <Link className="hover:underline" href="#">
              Privacy
            </Link>
            <Link className="hover:underline" href="#">
              Contact
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function ActivityIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2" />
    </svg>
  )
}


function ChevronRightIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function FilePenIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function RssIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 11a9 9 0 0 1 9 9" />
      <path d="M4 4a16 16 0 0 1 16 16" />
      <circle cx="5" cy="19" r="1" />
    </svg>
  )
}


function UserIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function UserPlusIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <line x1="19" x2="19" y1="8" y2="14" />
      <line x1="22" x2="16" y1="11" y2="11" />
    </svg>
  )
}


function UsersIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
